{
	auto_https off
}

:80 {
	root * /var/www/certbot
	handle /.well-known/acme-challenge/* {
		file_server
	}

	handle_path /kaziro-api/* {
		reverse_proxy host.docker.internal:8001
	}

	handle_path /media/* {
		root * /srv/media
		file_server
	}

	handle {
		reverse_proxy web:8000
	}
}
