# Generated by Django 6.0.6 on 2026-06-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nav_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="open_graph_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="open_graph_title",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="profile",
            name="seo_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="seo_title",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="profile",
            name="skill_copy",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="skill_heading",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="profile",
            name="ui_copy",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="profile",
            name="about_heading",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_heading",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
