# Generated by Django 6.0.6 on 2026-06-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_profile_nav_links_profile_open_graph_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certification",
            name="certificate_file",
        ),
        migrations.AddField(
            model_name="certification",
            name="static_asset_path",
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
