# Generated by Codex on 2026-06-10

from django.db import migrations, models


DEFAULT_TRUST_ITEMS = [
    "Fintech",
    "SaaS",
    "E-commerce",
    "Social impact",
    "AI-enabled products",
    "Global remote teams",
]

DEFAULT_SERVICE_ITEMS = [
    {
        "step": "01",
        "title": "Plan",
        "summary": "Clarify the product, architecture, delivery path, and risks before teams commit budget.",
        "outcome": "A practical roadmap with scope, milestones, and technical tradeoffs made visible.",
    },
    {
        "step": "02",
        "title": "Build",
        "summary": "Design and ship reliable full-stack products across web, mobile, APIs, and applied AI workflows.",
        "outcome": "Production software that is maintainable, observable, and ready for real users.",
    },
    {
        "step": "03",
        "title": "Lead",
        "summary": "Guide teams through planning, reviews, delivery rituals, mentoring, and technical decisions.",
        "outcome": "Engineering teams that move faster without losing quality or alignment.",
    },
    {
        "step": "04",
        "title": "Maintain",
        "summary": "Stabilize systems with testing, CI/CD, documentation, monitoring, and pragmatic refactoring.",
        "outcome": "Lower operational drag and a codebase future teams can confidently extend.",
    },
]

DEFAULT_FEATURED_PROJECTS = [
    {
        "title": "FieldEntry Survey Aggregation",
        "client": "Rainforest Alliance",
        "status": "Delivered",
        "problem": "Certificate holders needed a clearer way to aggregate survey data from registered small farms.",
        "role": "Independent consultant owning product architecture and implementation.",
        "stack": ["React", "FastAPI", "Electron", "KoBo", "Python"],
        "outcome": "Delivered an end-to-end data tool within 3 months, improving survey aggregation and reporting workflows.",
    },
    {
        "title": "Greenhouse Gas Desktop Tool",
        "client": "Rainforest Alliance",
        "status": "Delivered",
        "problem": "Teams needed a desktop workflow for greenhouse gas calculations across multiple farms.",
        "role": "Designed the frontend, backend API, and integration path for farm-level calculation data.",
        "stack": ["Electron", "React", "FastAPI", "Cool Farm API"],
        "outcome": "Connected KoBo survey data to calculation APIs and packaged the workflow into a usable desktop app.",
    },
    {
        "title": "AI-assisted Lexicon Platform",
        "client": "Teknobyte",
        "status": "Delivered",
        "problem": "Language data workflows needed stronger quality controls and more efficient review tooling.",
        "role": "Engineering lead building administrative tools and applying LLMs to proof-checking workflows.",
        "stack": ["React", "Python", "LLMs", "Data tooling"],
        "outcome": "Reduced data corruption and supported smarter review flows with AI-assisted suggestions.",
    },
]


def populate_professional_sections(apps, schema_editor):
    Profile = apps.get_model("content", "Profile")

    for profile in Profile.objects.all():
        if not profile.trust_items:
            profile.trust_items = DEFAULT_TRUST_ITEMS
        if not profile.service_items:
            profile.service_items = DEFAULT_SERVICE_ITEMS
        if not profile.featured_projects:
            profile.featured_projects = DEFAULT_FEATURED_PROJECTS
        profile.save(update_fields=["trust_items", "service_items", "featured_projects", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_remove_certification_certificate_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="featured_projects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="resume_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="service_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="trust_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_professional_sections, migrations.RunPython.noop),
    ]
