# Generated by Codex on 2026-06-10

from django.db import migrations


def refine_existing_positioning(apps, schema_editor):
    Profile = apps.get_model("content", "Profile")

    ui_copy_defaults = {
        "hero_resume_action": "Download CV",
        "trust_section_label": "Trusted across",
        "services_section_label": "How I help",
        "featured_projects_label": "Selected proof",
        "featured_projects_intro": "A few examples of the kind of product, platform, and delivery work clients bring me into.",
        "project_problem_label": "Problem",
        "project_role_label": "Role",
        "project_outcome_label": "Outcome",
        "project_stack_label": "Stack",
        "experience_timeline_label": "Experience timeline",
    }

    for profile in Profile.objects.all():
        profile.headline = "I help teams ship\nreliable software."
        profile.bio = (
            "Senior full-stack engineer and technical lead helping teams ship reliable web, mobile, "
            "and AI-enabled products - from architecture and delivery planning to production code."
        )
        profile.ui_copy = {**ui_copy_defaults, **profile.ui_copy}
        profile.save(update_fields=["headline", "bio", "ui_copy", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_profile_professional_sections"),
    ]

    operations = [
        migrations.RunPython(refine_existing_positioning, migrations.RunPython.noop),
    ]
